version: '3.0'

services:
  main:
    container_name: backend-bot-game-gc-poker
    build: 
      context: .
    env_file: 
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports: 
     - 1000:1000
    command: npm run start
    restart: always