version: '4.29.0'

services:
  main:
    container_name: backend-bot-game-gc-poker
    build: 
      context: .
    env_file: 
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports: 
     - 1000:1000
    command: npm run start
    depends_on: 
      - postgres
      - redis
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: 
      - .env
    environment: 
      PG_DATA: /var/lib/postgresql/data
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: redis
    image: redis
    env_file: 
      - .env
    environment: 
      REDIS_DATA: /var/lib/redis/data
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data
    restart: always

volumes:
  pgdata:
  redis: