import { MigrationInterface, QueryRunner } from "typeorm";

export class AllianceMigration1718783877671 implements MigrationInterface {
    name = 'AllianceMigration1718783877671'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "FK_8106976d22064daaac5894ccf04"`);
        await queryRunner.query(`CREATE TYPE "public"."clubs_invitation_status_enum" AS ENUM('apply', 'reject', 'waiting')`);
        await queryRunner.query(`CREATE TABLE "clubs_invitation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."clubs_invitation_status_enum" NOT NULL DEFAULT 'waiting', "created_at" TIMESTAMP NOT NULL, "userId" uuid, "clubId" uuid, CONSTRAINT "PK_1532d74f25952949e16dbe5a721" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."club_settings_type_enum" AS ENUM('opened', 'closed')`);
        await queryRunner.query(`CREATE TYPE "public"."club_settings_default_role_enum" AS ENUM('member', 'moder', 'admin')`);
        await queryRunner.query(`CREATE TABLE "club_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."club_settings_type_enum" NOT NULL, "work_hours" character varying NOT NULL, "default_role" "public"."club_settings_default_role_enum" NOT NULL DEFAULT 'member', "coin_ration" double precision NOT NULL, "created_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_1d96d9afbb7d1f539b6d6aa9555" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."club_banned_and_kicked_users_type_enum" AS ENUM('kick', 'ban')`);
        await queryRunner.query(`CREATE TABLE "club_banned_and_kicked_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reason" character varying NOT NULL, "type" "public"."club_banned_and_kicked_users_type_enum" NOT NULL, "period_to" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL, "userId" uuid, "clubId" uuid, CONSTRAINT "PK_1a24f5b3c7399a6426ec1272e21" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invitation_links_type_enum" AS ENUM('club', 'alliance')`);
        await queryRunner.query(`CREATE TABLE "invitation_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."invitation_links_type_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL, "link" character varying NOT NULL, "time_period" TIMESTAMP NOT NULL, "allianceId" uuid, "clubId" uuid, CONSTRAINT "PK_78ebabba3f0478fbf7c16319b7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "news" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL, "link" character varying NOT NULL, "description" character varying NOT NULL, "clubId" uuid, "allianceId" uuid, CONSTRAINT "PK_39a43dfcb6007180f04aff2357e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "alliance_owners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "moder_username" character varying, "owner_username" character varying NOT NULL, "percent" double precision NOT NULL, "created_at" TIMESTAMP NOT NULL, "allianceId" uuid, CONSTRAINT "PK_8fcbc918c36fac485872f3e0b6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."alliance_localization_enum" AS ENUM('ru', 'en', 'ua', 'kk', 'ka', 'de')`);
        await queryRunner.query(`CREATE TYPE "public"."alliance_type_enum" AS ENUM('opened', 'closed')`);
        await queryRunner.query(`CREATE TABLE "alliance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "motto" character varying, "name" character varying NOT NULL, "avatar" character varying NOT NULL, "description" character varying NOT NULL, "coinRation" integer NOT NULL, "localization" "public"."alliance_localization_enum" NOT NULL, "type" "public"."alliance_type_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_4ca41472d33b43df4e3ac16c7a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."alliances_invitation_status_enum" AS ENUM('apply', 'reject', 'waiting')`);
        await queryRunner.query(`CREATE TABLE "alliances_invitation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."alliances_invitation_status_enum" NOT NULL DEFAULT 'waiting', "created_at" TIMESTAMP NOT NULL, "clubId" uuid, "allianceId" uuid, CONSTRAINT "PK_af52cd410916bbb08ce67486a08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tournament_settings_typeofgame_enum" AS ENUM('texas', 'ohama')`);
        await queryRunner.query(`CREATE TABLE "tournament_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "total_players" integer NOT NULL, "typeOfGame" "public"."tournament_settings_typeofgame_enum" NOT NULL, "buy_in" integer NOT NULL, "fee" double precision NOT NULL, "prizeDistribution" text NOT NULL, "default_user_balance" integer NOT NULL, "small_blind" integer NOT NULL, "big_blind" integer NOT NULL, "ante" integer, "time_decision_in_seconds" integer NOT NULL, "rest_time_in_minutes" integer NOT NULL, "created_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_4f82976e32daea25cc51ac28bdf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "attribute"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "fileLink"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP COLUMN "joinCost"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP COLUMN "alianceId"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "nickname"`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "img" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."clubs_localization_enum" AS ENUM('ru', 'en', 'ua', 'kk', 'ka', 'de')`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "localization" "public"."clubs_localization_enum" array NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "ownerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "chat_link" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "channel_link" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "slogan" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "restrictions" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "settingsId" uuid`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD CONSTRAINT "UQ_6725be92eeab72e7950171fb953" UNIQUE ("settingsId")`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "allianceOwnerId" uuid`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD CONSTRAINT "UQ_0a9e27765f1e133f560b8575670" UNIQUE ("allianceOwnerId")`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD "join_cost" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD "allianceId" uuid`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD "settingsId" uuid`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "UQ_e10b044961d38674a31c160116b" UNIQUE ("settingsId")`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "wallet_address" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "allianceId" uuid`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "clubId" uuid`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "tournamentId" uuid`);
        await queryRunner.query(`ALTER TABLE "clubs_invitation" ADD CONSTRAINT "FK_12bc5c2a44cc44d4a9eb110b0d5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clubs_invitation" ADD CONSTRAINT "FK_62103c4b212dbb15f435cfab8b1" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club_banned_and_kicked_users" ADD CONSTRAINT "FK_d21f4917bf417ec26eb4b4bbc98" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club_banned_and_kicked_users" ADD CONSTRAINT "FK_0ee3b4334cb6619490976a40fb3" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_links" ADD CONSTRAINT "FK_dc86f79e280d386c6ea834505d8" FOREIGN KEY ("allianceId") REFERENCES "alliance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_links" ADD CONSTRAINT "FK_62204fb2b88fb6d363119d8d3d9" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news" ADD CONSTRAINT "FK_27094e868b20a99da11466e64f8" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news" ADD CONSTRAINT "FK_c9ba00bcb8819ab67f463b78d68" FOREIGN KEY ("allianceId") REFERENCES "alliance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alliance_owners" ADD CONSTRAINT "FK_5f4492f6a5823e4815ce7e34434" FOREIGN KEY ("allianceId") REFERENCES "alliance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alliances_invitation" ADD CONSTRAINT "FK_cfaf89506a2f025f5b365ddc00d" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alliances_invitation" ADD CONSTRAINT "FK_78ea6c5659f2e5e9809eed96713" FOREIGN KEY ("allianceId") REFERENCES "alliance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD CONSTRAINT "FK_6725be92eeab72e7950171fb953" FOREIGN KEY ("settingsId") REFERENCES "club_settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD CONSTRAINT "FK_0a9e27765f1e133f560b8575670" FOREIGN KEY ("allianceOwnerId") REFERENCES "alliance_owners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "FK_dfe4c91f71a5024ac970c1171bb" FOREIGN KEY ("allianceId") REFERENCES "alliance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "FK_e10b044961d38674a31c160116b" FOREIGN KEY ("settingsId") REFERENCES "tournament_settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_b0110cbc54fcec222c6fe54760f" FOREIGN KEY ("allianceId") REFERENCES "alliance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_36d5bc0380695786dbc7599d72e" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_65521e85f8a5e75caed572f4e6f" FOREIGN KEY ("tournamentId") REFERENCES "tournaments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_65521e85f8a5e75caed572f4e6f"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_36d5bc0380695786dbc7599d72e"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_b0110cbc54fcec222c6fe54760f"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "FK_e10b044961d38674a31c160116b"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "FK_dfe4c91f71a5024ac970c1171bb"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP CONSTRAINT "FK_0a9e27765f1e133f560b8575670"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP CONSTRAINT "FK_6725be92eeab72e7950171fb953"`);
        await queryRunner.query(`ALTER TABLE "alliances_invitation" DROP CONSTRAINT "FK_78ea6c5659f2e5e9809eed96713"`);
        await queryRunner.query(`ALTER TABLE "alliances_invitation" DROP CONSTRAINT "FK_cfaf89506a2f025f5b365ddc00d"`);
        await queryRunner.query(`ALTER TABLE "alliance_owners" DROP CONSTRAINT "FK_5f4492f6a5823e4815ce7e34434"`);
        await queryRunner.query(`ALTER TABLE "news" DROP CONSTRAINT "FK_c9ba00bcb8819ab67f463b78d68"`);
        await queryRunner.query(`ALTER TABLE "news" DROP CONSTRAINT "FK_27094e868b20a99da11466e64f8"`);
        await queryRunner.query(`ALTER TABLE "invitation_links" DROP CONSTRAINT "FK_62204fb2b88fb6d363119d8d3d9"`);
        await queryRunner.query(`ALTER TABLE "invitation_links" DROP CONSTRAINT "FK_dc86f79e280d386c6ea834505d8"`);
        await queryRunner.query(`ALTER TABLE "club_banned_and_kicked_users" DROP CONSTRAINT "FK_0ee3b4334cb6619490976a40fb3"`);
        await queryRunner.query(`ALTER TABLE "club_banned_and_kicked_users" DROP CONSTRAINT "FK_d21f4917bf417ec26eb4b4bbc98"`);
        await queryRunner.query(`ALTER TABLE "clubs_invitation" DROP CONSTRAINT "FK_62103c4b212dbb15f435cfab8b1"`);
        await queryRunner.query(`ALTER TABLE "clubs_invitation" DROP CONSTRAINT "FK_12bc5c2a44cc44d4a9eb110b0d5"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "tournamentId"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "clubId"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "allianceId"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "wallet_address"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "UQ_e10b044961d38674a31c160116b"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP COLUMN "settingsId"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP COLUMN "allianceId"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP COLUMN "join_cost"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP CONSTRAINT "UQ_0a9e27765f1e133f560b8575670"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "allianceOwnerId"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP CONSTRAINT "UQ_6725be92eeab72e7950171fb953"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "settingsId"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "restrictions"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "slogan"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "channel_link"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "chat_link"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "localization"`);
        await queryRunner.query(`DROP TYPE "public"."clubs_localization_enum"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "img"`);
        await queryRunner.query(`ALTER TABLE "clubs" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "nickname" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD "alianceId" uuid`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD "joinCost" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "fileLink" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clubs" ADD "attribute" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "tournament_settings"`);
        await queryRunner.query(`DROP TYPE "public"."tournament_settings_typeofgame_enum"`);
        await queryRunner.query(`DROP TABLE "alliances_invitation"`);
        await queryRunner.query(`DROP TYPE "public"."alliances_invitation_status_enum"`);
        await queryRunner.query(`DROP TABLE "alliance"`);
        await queryRunner.query(`DROP TYPE "public"."alliance_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alliance_localization_enum"`);
        await queryRunner.query(`DROP TABLE "alliance_owners"`);
        await queryRunner.query(`DROP TABLE "news"`);
        await queryRunner.query(`DROP TABLE "invitation_links"`);
        await queryRunner.query(`DROP TYPE "public"."invitation_links_type_enum"`);
        await queryRunner.query(`DROP TABLE "club_banned_and_kicked_users"`);
        await queryRunner.query(`DROP TYPE "public"."club_banned_and_kicked_users_type_enum"`);
        await queryRunner.query(`DROP TABLE "club_settings"`);
        await queryRunner.query(`DROP TYPE "public"."club_settings_default_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."club_settings_type_enum"`);
        await queryRunner.query(`DROP TABLE "clubs_invitation"`);
        await queryRunner.query(`DROP TYPE "public"."clubs_invitation_status_enum"`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "FK_8106976d22064daaac5894ccf04" FOREIGN KEY ("alianceId") REFERENCES "aliance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
