version: '3.8'

services:
  react-app:
    build: .
    container_name: react-app
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/var/www/dist
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - react-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
